### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by EryouHao** [fwouts/electron-vue-typescript-starter#4]
thanks for your the starter project.

I met an error is: ERROR in unknown: Duplicate declaration "module", when I run `npm run build`, can you help me?
![image](https://user-images.githubusercontent.com/17328747/50502433-24ca7480-0a9a-11e9-988a-33264c72790a.png)

**Comment by fwouts** [comment]
Which version of Node are you using? Please run `node --version`.

**Comment by EryouHao** [comment]
the node version is `v10.0.0`

**Comment by fwouts** [comment]
Hi @EryouHao, do you mind pulling the latest master, running `node run build:clean` and trying again?

I've added a job specifically running a Node 10.0.0 build on CircleCI and there doesn't seem to be any issue: https://circleci.com/gh/fwouts/electron-vue-typescript-starter/12 (note this uses `yarn install` and not `npm install`).

**Comment by EryouHao** [comment]
thanks, I have already adopted other schemes to develop it.
